dnascope_model: "dnascope.model"
bwa_model: "bwa.model"
pcr_free: "false"
reference_fasta: "/home/ec2-user/haffener_test_dir/ref_genomes/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna"
cnv_model: "cnv.model"
sentieon_dir: "/home/ec2-user/sentieon-genomics-202308.03"
samtools_dir: "/home/ec2-user/samtools-1.21/samtools"
pangenome_vcf: "/home/ec2-user/haffener_test_dir/cactus_filtered_ids.vcf"
pangenome_data_dir: "/home/ec2-user/haffener_test_dir/pangenome_input_data"
pangenome_data_prefix: "cactus_filtered"
biallelic_vcf: "/home/ec2-user/haffener_test_dir/cactus_filtered_ids_biallelic.vcf.gz"
s3_bucket_out: "s3://secondary-test-data"
# Sentieon Bundles
sentieon_complete_mgi_wgs_bundle: "/home/ec2-user/DNAscopeMGIWGS2.0.bundle"
sentieon_complete_mgi_wes_bundle: "/home/ec2-user/DNAscopeMGIWES2.1.bundle"
sentieon_element_wgs_bundle:  "/home/ec2-user/DNAscopeElementBioWGS2.1.bundle"
sentieon_element_wes_bundle: "/home/ec2-user/DNAscopeElementBioWES2.1.bundle"
sentieon_illumina_wgs_bundle : "/home/ec2-user/SentieonIlluminaWGS2.2.bundle"
sentieon_illumina_wes_bundle: "/home/ec2-user/DNAscopeIlluminaWES2.1.bundle"
